### ISSUE TITLE
Add Array Based Algorithms.

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/hacktoberfest2022-DSA#3]

**Comment by imNilabja** [comment]
i would like to do this task,can you please assign this to me.

**Comment by CodeexpartPrakashGithub** [comment]
Please assign me this issue i want to contribute on it

**Comment by Mridul-1-Sharma** [comment]
Ok assigned to both of you now start contributing

**Comment by deepesh85b** [comment]
@Mridul-1-Sharma 
Please assign this to me

**Comment by prakharjadaun** [comment]
Hey @Mridul-1-Sharma, can you please assign this issue to me?
I am looking forward to contribute in hacktoberfest 2022. I will ensure that I follow all the rules strictly and contribute to your repo as much as I can.

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
