### ISSUE TITLE
Add Popular Interview DSA questions.

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/hacktoberfest2022-DSA#4]

**Comment by Mridul-1-Sharma** [comment]
> Hi can you assign this task me? I would like to contribute

OK ASSIGNED NOW START CONTRIBUTING

**Comment by imNilabja** [comment]
I can do this task ,could you assign me this task

**Comment by harsh0620** [comment]
Hi there, Can you assign me this task. I want to contribute.

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
