### ISSUE TITLE
I want to add Prims,kurskal and Djiskta algorithm of DSA in your repository

### ISSUE THREAD

**Issue by mdzeeshan-2** [Mridul-1-Sharma/hacktoberfest2022-DSA#47]
Please allow me to do.

**Comment by Mridul-1-Sharma** [comment]
Djiskta algorithm already contributed by someone, but you can add others.I am assigning this issue to you so that you can contribute.

**Comment by sohampathak1234** [comment]
Hey @Mridul-1-Sharma  , Can you assign me this issue too?

**Comment by mdzeeshan-2** [comment]
Thank You so much, Okay am adding prims kurshkal algorithm

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
