### ISSUE TITLE
add leetcode Questions

### ISSUE THREAD

**Issue by interestingsanskar07** [Mridul-1-Sharma/hacktoberfest2022-DSA#49]
please add leetcode questions .
allow me to contribute.

**Comment by Mridul-1-Sharma** [comment]
yes please add. I am assigning it to you

**Comment by suresh37** [comment]
@Mridul-1-Sharma  I have added binary search program in java. please check and merge PR

LC: https://leetcode.com/problems/binary-search/

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
