### ISSUE TITLE
Add Bit Manipulation Algorithms

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/hacktoberfest2022-DSA#5]

**Comment by CodeexpartPrakashGithub** [comment]
Please assign this to me

**Comment by Mridul-1-Sharma** [comment]
> Please assign this to me

ok

**Comment by harsh0620** [comment]
Hi there, Can you please assign me this task.

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
