### ISSUE TITLE
Add Competitive Programing Questions from leetcode, geeksforgeeks, codechef etc.

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/hacktoberfest2022-DSA#6]

**Comment by Tusharsolanki077** [comment]
Hey @Mridul-1-Sharma Please assign this task to me.

**Comment by Mridul-1-Sharma** [comment]
> Hey @Mridul-1-Sharma Please assign this task to me.

Assigned to you now start contributing

**Comment by Dnyanesh-Bachhav** [comment]
Hey can you assign this task me??

**Comment by Mridul-1-Sharma** [comment]
> Hey can you assign this task me??

OK ASSIGNED

**Comment by pk21-praveen** [comment]
Hi can you assign this task me? I would like to contribute

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
