### ISSUE TITLE
I want to add the code of Largest Rectangle in Histogram(Stack)

### ISSUE THREAD

**Issue by itzanushka07** [Mridul-1-Sharma/hacktoberfest2022-DSA#62]

**Comment by Debayan97531** [comment]
Please assign me this issue @Mridul-1-Sharma ..I can solve this.

**Comment by Debayan97531** [comment]
Will you kindly label this question as hacktoberfest..and accept my pr?

**Comment by Debayan97531** [comment]
#72

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
