### ISSUE TITLE
Add Algorithms for data Structures like stack, queue, link list etc

### ISSUE THREAD

**Issue by Mridul-1-Sharma** [Mridul-1-Sharma/hacktoberfest2022-DSA#7]
Add algos for their creation, deletion, traversal etc.

**Comment by jay13makhija** [comment]
Please assign me this issue

**Comment by imNilabja** [comment]
i would like to do this task,can you please assign this to me.

**Comment by Wolverine-08** [comment]
@Mridul-1-Sharma hii sir can please assign it me

**Comment by Mridul-1-Sharma** [comment]
Ok assigned to both of you

**Comment by prakharjadaun** [comment]
Hey @Mridul-1-Sharma can you assign this issue to me too?

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
