### ISSUE TITLE
Add scheduling Algorithms

### ISSUE THREAD

**Issue by 1447bits** [Mridul-1-Sharma/hacktoberfest2022-DSA#75]
Scheduling Algorithms like Shortest job First, First Come First Serve, Priority Basis Scheduling.

**Comment by Abhishek-Vaidya** [comment]
I can work on this issue can I solve it?

**Comment by Mridul-1-Sharma** [comment]
This repository is excluded from hacktoberfest if want to contribute you can contribute in https://github.com/Mridul-1-Sharma/data_structures_algos
